// JavaScript Document
var cText = ''
cText += '  <div id="footer_container" class="container_18">'
cText += '    <div class="grid_18" id="trends">'
cText += '      <div class="current">'
cText += '        <ul>'
cText += '          <li><a target="_blank" href="#">About Us</a></li>' 
cText += '          <li><a target="_blank" href="#">Contact Us</a></li>'

cText += '                 <li class="footerRightCorner"><a target="_blank" href="#"> '
cText += '                     <img src="resources/images/twitter-icon.gif"'
cText += '                          title="twitter" alt="twitter"></a></li> '

cText += '  <li class="footerRightCorner"><a target="_blank" href="#"> '
cText += '                    <img src="resources/images/facebook-icon.gif"'
cText += '                          title="facebook" alt="facebook"></a></li> '


cText += '        </ul>'
cText += '      </div>'
cText += '    </div>'
cText += '    <div class="grid_18">'
cText += '      <!--[if IE]>'
cText += '        <div class="wrapper-footer-ie left-corner">'
cText += '            <div class="right-corner">'
cText += '            </div>'
cText += '        </div>'
cText += '        <![endif]-->'
cText += '      <div id="footer" class="round">'
cText += '        <ul>'
cText += '          <li class="first">&copy; 2013 smartSMS 13-009 SLIIT</li>'
cText += '        </ul>'
cText += '        <div id="clock" class="alignright">&nbsp;</div>'
cText += '        <div class="clear">&nbsp; </div>'
cText += '      </div>'
cText += '    </div>'
cText += '  </div>'
document.write(cText)
