-- CREATE DATABASE VIGRAHA
DROP DATABASE IF EXISTS `SMART-SMS`;
CREATE DATABASE IF NOT EXISTS `SMART-SMS`;

USE `SMART-SMS`;

DROP TABLE IF EXISTS `KEYWORD`;
CREATE TABLE IF NOT EXISTS `KEYWORD` (
`ID` VARCHAR(50) NOT NULL,
`APP_ID` VARCHAR(50) NOT NULL,
`NAME` VARCHAR(50) NOT NULL,
`SHORT_CODE` VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
)
ENGINE= InnoDB;;

DROP TABLE IF EXISTS `VOTING_APP`;
CREATE TABLE IF NOT EXISTS `VOTING_APP` (
`ID` VARCHAR(50) NOT NULL,
`NAME` VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(250) NOT NULL,
`START_DATE` DATETIME NOT NULL ,
`END_DATE` DATETIME NOT NULL,
PRIMARY KEY(ID)
)
ENGINE= InnoDB;

DROP TABLE IF EXISTS `CANDIDATE`;
CREATE TABLE IF NOT EXISTS `CANDIDATE` (
`VOTING_APP_ID` VARCHAR(50) NOT NULL,
`CODE` VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(250) NOT NULL,
`VOTES` INT NOT NULL,
PRIMARY KEY(VOTING_APP_ID,CODE)

)
ENGINE= InnoDB;

DROP TABLE IF EXISTS `SERVICE_APP`;
CREATE TABLE IF NOT EXISTS `SERVICE_APP` (
`ID` VARCHAR(50) NOT NULL,
`NAME` VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(250) NOT NULL,
`START_DATE` DATETIME NOT NULL ,
`END_DATE` DATETIME NOT NULL,
`SCHEDULE_TYPE` VARCHAR(50) NOT NULL,
`DISPATCH_TIME` VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
)
ENGINE= InnoDB;

DROP TABLE IF EXISTS `SUBSCRIBERS`;
CREATE TABLE IF NOT EXISTS `SUBSCRIBERS` (
`ID` VARCHAR(50) NOT NULL,
`APP_ID` VARCHAR(50) NOT NULL,
`SUBSCRIBER_NUMBER` VARCHAR(250) NOT NULL,
PRIMARY KEY(ID)
)
ENGINE= InnoDB;

DROP TABLE IF EXISTS `ALERT_APP`;
CREATE TABLE IF NOT EXISTS `ALERT_APP` (
`ID` VARCHAR(50) NOT NULL,
`NAME` VARCHAR(50) NOT NULL,
`DESCRIPTION` VARCHAR(250) NOT NULL,
`START_DATE` VARCHAR(100) NOT NULL ,
`END_DATE` VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
)
ENGINE= InnoDB;
